# -----------------------------------------------------------------------------------------------------------------------
#      Author: Ankit Goyal
#      Email : ankitgoyal.bpl@gmail.com
#------------------------------------------------------------------------------------------------------------------------

import urllib
from datetime import datetime
from BeautifulSoup import BeautifulSoup, SoupStrainer
from collections import defaultdict

# Global Constants
WEBSITE_ERROR_MSG = "Some Error while contacting WebSite. Please Try again later"
INPUT_ERROR_MSG = "Wrong Input entered. Exiting"
BMS_WEBSITE_ADDRESS = "http://in.bookmyshow.com"
# Hard-Coded for now. Need to find a way to get a lsit of Cities
CITY_NAME = "hyderabad"
BMS_MOVIES_WEBPAGE = "movies"

# Function to get list of movies in a City
# both Now Showing and Next Change
def GetMoviesList() :
      try :
            pageContent = urllib.urlopen('/'.join([BMS_WEBSITE_ADDRESS, CITY_NAME, BMS_MOVIES_WEBPAGE])).read()
            onlyMovieTags = SoupStrainer("a", "mvCnt")
            movieSoup = BeautifulSoup(pageContent, parseOnlyThese=onlyMovieTags)
      except : 
            print WEBSITE_ERROR_MSG
            exit()

      if len(movieSoup) < 1 :
            return None

      # TODO: Make sure that we need a dictionary over here and not list. If not convert this to a list of tuples
      movieDict = defaultdict(list)
      for movieData in movieSoup :
            movieDict[movieData["data"]].append(movieData["href"])
            movieDict[movieData["data"]].append(movieData["title"])

      return movieDict

# Function to ask for User Input to select a movie out of list
# of movies in his/her city
def SelectMovie(movieDict) :      
      movieCounter = 1
      for movieItem in movieDict.values() :
            print movieCounter, movieItem[1]
            movieCounter = movieCounter + 1

      inputIndex = raw_input("Please Enter your Movie Choice: ")
      try :
            choosenIndex = int(inputIndex) - 1
      except : 
            print INPUT_ERROR_MSG
            exit()

      return movieDict.values()[choosenIndex]

# For Now I have Hard-Coded the values as
# the list of theater is generated by JavaScript
# and need to dig more into that.
def GetListofTheaters() :
      theaterList = list()
      theaterList.append(["PVR Sujana Forum Fiza Mall: Kukatpally", "PVSF"])
      theaterList.append(["Cinepolis: Manjeera Mall, Hyderabad", "CPMH"])
      theaterList.append(["PVR: Cyberabad, Inorbit Mall", "CXCB"])
      theaterList.append(["PVR: Banjara Hills", "CXHY"])
      theaterList.append(["Prasads: Hyderabad", "PRHN"])
      return theaterList

# Function to ask user for the choice of his/her theater
def SelectTheater(theaterList) :
      theaterCounter = 1
      for theaterInfo in theaterList :
            print theaterCounter, theaterInfo[0]
            theaterCounter = theaterCounter + 1

      inputIndex = raw_input("Please Enter your Theater Choice: ")
      try :
            choosenIndex = int(inputIndex) - 1
      except : 
            print INPUT_ERROR_MSG
            exit()

      return theaterList[choosenIndex]

def GetDateOfMovie() :
      inputValue = raw_input("Please Enter the Date (within 2 days from now) in following format (YYYYMMDD) : ")
      try : 
            inputDate = datetime.strptime(inputValue, "%Y%m%d")
      except : 
            print INPUT_ERROR_MSG
            exit()

      todaysDate = datetime.now()
      if  (inputDate - todaysDate).days < 0 or (inputDate - todaysDate).days > 2: 
            print INPUT_ERROR_MSG
            exit()

      return inputValue



print SelectMovie(GetMoviesList())
print SelectTheater(GetListofTheaters())
print GetDateOfMovie()